from dataclasses import dataclass
from datetime import UTC, datetime

from app.github.github_service import (
    create_blob,
    create_commit,
    create_pull_request,
    create_ref,
    create_tree,
    get_git_commit,
    get_ref,
    update_ref,
)
from app.services.patch_service import PatchedFile


@dataclass(frozen=True)
class FixCommitResult:
    branch_name: str
    commit_sha: str
    commit_url: str | None
    pull_request_number: int | None
    pull_request_url: str | None


class GitCommitService:
    def create_fix_commit(
        self,
        repository: str,
        base_branch: str,
        expected_head_sha: str,
        patched_files: list[PatchedFile],
        access_token: str,
        pull_request_number: int,
        mode: str,
    ) -> FixCommitResult:
        current_head_sha = self._get_branch_head_sha(
            repository=repository,
            branch_name=base_branch,
            access_token=access_token,
        )
        if current_head_sha != expected_head_sha:
            raise ValueError("Target branch HEAD changed after fixes were generated")

        target_branch = base_branch
        pull_request_url = None
        pull_request_number_result = None
        if mode == "BRANCH_PR":
            target_branch = self._create_fix_branch(
                repository=repository,
                pull_request_number=pull_request_number,
                source_sha=expected_head_sha,
                access_token=access_token,
            )

        commit = self._commit_files(
            repository=repository,
            branch_name=target_branch,
            parent_sha=expected_head_sha,
            patched_files=patched_files,
            access_token=access_token,
        )

        if mode == "BRANCH_PR":
            pull_request = create_pull_request(
                repository=repository,
                head_branch=target_branch,
                base_branch=base_branch,
                title=f"AI fixes for PR #{pull_request_number}",
                body=(
                    "This pull request was generated by the AI Code Review Assistant "
                    "from explicitly selected review fixes."
                ),
                access_token=access_token,
            )
            pull_request_url = pull_request.get("html_url")
            pull_request_number_result = pull_request.get("number")

        return FixCommitResult(
            branch_name=target_branch,
            commit_sha=commit["sha"],
            commit_url=commit.get("html_url"),
            pull_request_number=pull_request_number_result,
            pull_request_url=pull_request_url,
        )

    def _get_branch_head_sha(
        self,
        repository: str,
        branch_name: str,
        access_token: str,
    ) -> dict:
        ref = get_ref(
            repository=repository,
            branch_name=branch_name,
            access_token=access_token,
        )
        return ref["object"]["sha"]

    def _create_fix_branch(
        self,
        repository: str,
        pull_request_number: int,
        source_sha: str,
        access_token: str,
    ) -> str:
        timestamp = datetime.now(UTC).strftime("%Y%m%d%H%M%S")
        branch_name = f"ai-fix/{pull_request_number}-{timestamp}"
        create_ref(
            repository=repository,
            branch_name=branch_name,
            sha=source_sha,
            access_token=access_token,
        )
        return branch_name

    def _commit_files(
        self,
        repository: str,
        branch_name: str,
        parent_sha: str,
        patched_files: list[PatchedFile],
        access_token: str,
    ) -> str:
        parent_commit = get_git_commit(
            repository=repository,
            commit_sha=parent_sha,
            access_token=access_token,
        )
        tree_items = []
        for patched_file in patched_files:
            blob = create_blob(
                repository=repository,
                content=patched_file.patched_content,
                access_token=access_token,
            )
            tree_items.append(
                {
                    "path": patched_file.file_path,
                    "mode": "100644",
                    "type": "blob",
                    "sha": blob["sha"],
                }
            )

        tree = create_tree(
            repository=repository,
            base_tree_sha=parent_commit["tree"]["sha"],
            tree_items=tree_items,
            access_token=access_token,
        )
        commit = create_commit(
            repository=repository,
            message="Apply AI suggested fixes",
            tree_sha=tree["sha"],
            parent_sha=parent_sha,
            access_token=access_token,
        )
        update_ref(
            repository=repository,
            branch_name=branch_name,
            sha=commit["sha"],
            access_token=access_token,
            force=False,
        )

        return commit
