"""added commit sha column to review

Revision ID: a15ed06e84de
Revises: deefb77c04c5
Create Date: 2026-06-20 22:53:39.153202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15ed06e84de'
down_revision: Union[str, Sequence[str], None] = 'deefb77c04c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('commit_sha', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'commit_sha')
    # ### end Alembic commands ###
