"""add issue line number

Revision ID: deefb77c04c5
Revises: 2e8b454d299b
Create Date: 2026-06-16 20:57:41.081096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deefb77c04c5'
down_revision: Union[str, Sequence[str], None] = '2e8b454d299b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('line', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'line')
    # ### end Alembic commands ###
